"""empty message

Revision ID: 1157f8b20d43
Revises: 8ef307a96d0d
Create Date: 2023-07-12 22:25:49.550988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1157f8b20d43'
down_revision = '8ef307a96d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
