"""empty message

Revision ID: 3a30b21bb7b5
Revises: 1157f8b20d43
Create Date: 2023-07-12 22:28:21.180913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a30b21bb7b5'
down_revision = '1157f8b20d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ciudad_fkey', type_='foreignkey')
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comment_ciudad_fkey', 'city', ['ciudad'], ['name'])

    # ### end Alembic commands ###
