"""empty message

Revision ID: dc661ba5c70f
Revises: fc5a39f68434
Create Date: 2023-07-14 23:05:49.395364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc661ba5c70f'
down_revision = 'fc5a39f68434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_city_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_city_id_fkey', 'country', ['city_id'], ['id'])

    # ### end Alembic commands ###
